# Generated by Django 5.1.1 on 2024-09-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maungawhau', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
