# Generated by Django 5.1.1 on 2024-09-14 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maungawhau', '0004_courseclass_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeday',
            name='students',
        ),
        migrations.AddField(
            model_name='courseclass',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Maungawhau.semester'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
