# Generated by Django 5.1.1 on 2024-09-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maungawhau', '0006_lecturer_address_lecturer_phone_student_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='staff_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
