# Generated by Django 5.1.1 on 2024-09-14 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maungawhau', '0007_alter_lecturer_staff_id_alter_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maungawhau.courseclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maungawhau.student')),
            ],
        ),
    ]
