# Generated by Django 5.1.1 on 2024-09-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maungawhau', '0008_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseclass',
            name='students',
        ),
    ]
