# Generated by Django 5.1.1 on 2024-09-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maungawhau', '0009_remove_courseclass_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
