# Generated by Django 5.1.1 on 2024-09-16 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maungawhau', '0010_delete_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseclass',
            name='image',
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='lecturers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Maungawhau.lecturer'),
        ),
    ]
