# Generated by Django 5.1.1 on 2024-09-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maungawhau', '0011_remove_courseclass_image_alter_courseclass_lecturers'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeday',
            name='student',
            field=models.ManyToManyField(to='Maungawhau.student'),
        ),
    ]
