# Generated by Django 5.1.1 on 2024-09-17 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maungawhau', '0012_collegeday_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeday',
            name='friday_slot1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday_slot1', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='friday_slot2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday_slot2', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='friday_slot3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday_slot3', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='friday_slot4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday_slot4', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='friday_slot5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday_slot5', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='monday_slot1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_slot1', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='monday_slot2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_slot2', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='monday_slot3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_slot3', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='monday_slot4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_slot4', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='monday_slot5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_slot5', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='thursday_slot1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_slot1', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='thursday_slot2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_slot2', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='thursday_slot3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_slot3', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='thursday_slot4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_slot4', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='thursday_slot5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_slot5', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='tuesday_slot1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_slot1', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='tuesday_slot2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_slot2', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='tuesday_slot3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_slot3', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='tuesday_slot4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_slot4', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='tuesday_slot5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_slot5', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='wednesday_slot1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_slot1', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='wednesday_slot2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_slot2', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='wednesday_slot3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_slot3', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='wednesday_slot4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_slot4', to='Maungawhau.courseclass'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='wednesday_slot5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_slot5', to='Maungawhau.courseclass'),
        ),
        migrations.AlterField(
            model_name='collegeday',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
