# Generated by Django 5.1.1 on 2024-09-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maungawhau', '0013_collegeday_friday_slot1_collegeday_friday_slot2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeday',
            name='date',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='friday_slot1',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='friday_slot2',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='friday_slot3',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='friday_slot4',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='friday_slot5',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='monday_slot1',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='monday_slot2',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='monday_slot3',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='monday_slot4',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='monday_slot5',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='thursday_slot1',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='thursday_slot2',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='thursday_slot3',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='thursday_slot4',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='thursday_slot5',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='tuesday_slot1',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='tuesday_slot2',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='tuesday_slot3',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='tuesday_slot4',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='tuesday_slot5',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='wednesday_slot1',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='wednesday_slot2',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='wednesday_slot3',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='wednesday_slot4',
        ),
        migrations.RemoveField(
            model_name='collegeday',
            name='wednesday_slot5',
        ),
        migrations.AddField(
            model_name='collegeday',
            name='attendance_status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=10),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='collegeday',
            name='student',
            field=models.ManyToManyField(blank=True, to='Maungawhau.student'),
        ),
    ]
