# Generated by Django 5.1.1 on 2024-09-18 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maungawhau', '0015_remove_collegeday_attendance_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], default='A', max_length=1)),
                ('college_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maungawhau.collegeday')),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maungawhau.courseclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_view_lecturer_attendance', 'Can view lecturer attendance'), ('can_enter_attendance', 'Can enter attendance')],
            },
        ),
    ]
