# Generated by Django 5.1.1 on 2024-09-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maungawhau', '0016_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeday',
            name='student',
            field=models.ManyToManyField(related_name='college_days', to='Maungawhau.student'),
        ),
    ]
