# Generated by Django 5.1.1 on 2024-09-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maungawhau', '0017_alter_collegeday_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
